### ISSUE TITLE
Dynamic period table capacity adjustment

### ISSUE THREAD

**Issue by awh** [weaveworks/cortex#464] opened 2017-06-19 10:04 UTC
During the period from midnight to midnight + max chunk age, newly matured chunks require 2x the number of index entries to be written to the period tables because their contents span two day buckets. Provisioned capacity must be sized to cope with this nightly spike or the series flush queues start to back up:

![screenshot from 2017-06-19 10-56-08](https://user-images.githubusercontent.com/1504438/27280132-c5bd506a-54de-11e7-84a8-0efc61557678.png)
![screenshot from 2017-06-19 10-56-31](https://user-images.githubusercontent.com/1504438/27280139-cbc3becc-54de-11e7-849f-28789d482dda.png)

However, doing so means that capacity is over-provisioned for the noon to midnight period. The table manager can be enhanced to step the capacity up automatically before midnight, and back down again after noon.

**Comment by tomwilkie** [comment] 2017-06-19 10:12
Dupe of #318?  @leth added metrics on per-tables used capacity in #460, which is the first step in dynamically adjusting provisioning.

**Comment by leth** [comment] 2017-06-19 10:45
The scope of this could be a bit smaller; just focused on the midnight rollover, rather than general capacity?

**Comment by tomwilkie** [comment] 2017-06-19 10:57
Thats up to the person who implements it I guess!  I personally don't see how just focusing on the time around midnight make is much easier.

**Comment by awh** [comment] 2017-06-19 14:24
I suspect the solution for #318 will be far more complex than adding `if time > midnight & time < noon activeCapacity *= 2` to the table manager...

**Comment by bboreham** [comment] 2018-02-05 10:45
Do we still need this issue now autoscaling is supported?

**Comment by bboreham** [comment] 2018-09-06 07:02
I think the new metrics-based scaling in table-manager is coping ok with this, so closing this issue.

**Closed by bboreham** 2018-09-06 07:02 UTC
Labels: type/feature
