### ISSUE TITLE
Ingesters never disappear from ring if shut down ungracefully

### ISSUE THREAD

**Issue by ekimekim** [weaveworks/cortex#25] opened 2016-09-17 04:43 UTC
Related to https://github.com/weaveworks/frankenstein/issues/9

Right now, the only way an ingester is ever removed from the ring is if it shuts down gracefully. In any other circumstance (crash, network partition, asteroid strike) nothing will ever invalidate the old entries, until such a time as an ingester with the same hostname reconnects. This in turn means a large number of failing operations, requiring operator intervention.

This issue is less pronounced in most environments, where a crashed ingester typically will be swiftly restarted with an identical hostname. It could easily occur if an error occurred during, say, a rolling upgrade in k8s (new pod = new hostname). Note however that I haven't seen it in the wild. Yet.

**Comment by jml** [comment] 2016-09-26 13:53
This bit me in dev just now (I think). Nothing special in the rollout, just a new version of the image. I don't think that counts as a graceless shut down.

**Comment by jml** [comment] 2016-09-26 13:55
distributor logs had:
```
time="2016-09-26T13:44:52Z" level=info msg="Got update to ring - 8 ingesters, 1024 tokens" source="ring.go:85"
time="2016-09-26T13:44:52Z" level=info msg="POST /api/prom/push (500) 5.001240884s"
time="2016-09-26T13:44:53Z" level=info msg="POST /api/prom/push (500) 5.001266047s"
time="2016-09-26T13:44:53Z" level=info msg="POST /api/prom/push (500) 5.001311916s"
```

But there were only 4 ingesters:
$ kubectl get --namespace prism po --selector=name=ingester
```
NAME                        READY     STATUS    RESTARTS   AGE
ingester-3936767956-01wjs   1/1       Running   0          14m
ingester-3936767956-1rdo2   1/1       Running   0          14m
ingester-3936767956-g6ytq   1/1       Running   0          14m
ingester-3936767956-rn090   1/1       Running   0          14m
```

Restarting consul fixed it:

```
$ kubectl delete --namespace prism po --selector=name=consul
pod "consul-371475310-2yn19" deleted
pod "consul-371475310-4wwpm" deleted
pod "consul-371475310-f8rgq" deleted
```

**Comment by jml** [comment] 2016-09-30 11:13
And again with a rollout of ingesters today.

**Comment by tomwilkie** [comment] 2016-11-04 09:37
This is by design.  The design can only tolerate one failed ingester at anyone time.

It occurred to me it might be safe to GC a single dead ingester are an hour (the chunk flush deadline), as its guaranteed the other copy of the state will have hit S3.  But this might be tricky to get right.

**Comment by tomwilkie** [comment] 2016-11-11 14:56
Closing as we've done many successful roll outs now.

**Closed by tomwilkie** 2016-11-11 14:56 UTC
