### ISSUE TITLE
don't lose data during a prom->cortex network disruption

### ISSUE THREAD

**Issue by rade** [weaveworks/cortex#263] opened 2017-02-03 20:35 UTC
Cortex is great at keeping your metric data. But it can only keep what it receives, and atm a prometheus sending to cortex will simply throw data away on network disruption.

**Comment by juliusv** [comment] 2017-02-04 01:14
Yeah, that's by design on the Prometheus side so far. I think we'd be reluctant to introduce any meaningful retry buffers there (they can really blow Prometheus's memory up, plus they only help for a very brief outage anyways).

**Comment by rade** [comment] 2017-02-04 09:10
Think of buffers in the app as extensions of the tcp networking socket buffers.

**Comment by tomwilkie** [comment] 2017-02-04 09:20
There are already small buffers in Prometheus that can be quite easily
extended; in practice they run out very quickly.

We should define what type of error codes Prometheus will retry the sending
of batches on.  And make the buffers configurable. And probably do
something about the queue sharding, as it only works up to a certain rate
of samples/s given upstream latency.

**Comment by tomwilkie** [comment] 2017-03-20 11:12
Filed https://github.com/prometheus/prometheus/issues/2512 upstream, hoping to work on it this week.

**Comment by tomwilkie** [comment] 2017-04-07 10:26
Upstream is merged

**Closed by tomwilkie** 2017-04-07 10:26 UTC
Labels: feature
