### ISSUE TITLE
ingesters grind to a halt if > 1 week old samples are pushed

### ISSUE THREAD

**Issue by ekimekim** [weaveworks/cortex#518] opened 2017-07-24 20:08 UTC
If any significant number of samples are pushed to cortex which map to an 'inactive' dynamo table (ie. not the current week), they can only be written at a global throughput limit of 1 chunk/second. In the meantime, all ingesters are trying and failing to write these bad chunks, resulting in a large queue and very little useful work being performed.

To fix this, we need to do one of the following:
* Reject samples that are too old
* Increase limits dynamically on older tables (an extension of the work in https://github.com/weaveworks/cortex/pull/507)

**Comment by jml** [comment] 2017-09-07 12:21
@aaron7 & @bboreham have been looking into this. I have not, so de-assigning.

**Comment by aaron7** [comment] 2017-09-07 13:02
The current plan to migrate the problem is to enable write auto scaling for the last N inactive tables.

We haven't decided whether to reject old samples yet.

**Comment by jml** [comment] 2017-09-19 16:09
@aaron7 can we close this bug now?

**Comment by aaron7** [comment] 2017-09-19 16:20
Yes, #556 will migrate the problem for us.

**Closed by aaron7** 2017-09-19 16:20 UTC
Labels: bug, postmortem
