### ISSUE TITLE
0-value data in cortex-ui but not plain prom

### ISSUE THREAD

**Issue by rade** [weaveworks/cortex#304] opened 2017-02-27 18:44 UTC
The following graphs are all for the query
```
sum(rate(container_cpu_usage_seconds_total{image!=""}[5m])) by (pod_name, namespace)
```
and were executed at the same time on cortex-dev, prom-dev, cortex-prod, and prom-prod:
![screenshot_2017-02-27_18-45-46](https://cloud.githubusercontent.com/assets/109109/23374634/fc333e1c-fd1c-11e6-93d2-7861c2a5267c.png)
![screenshot_2017-02-27_18-38-30](https://cloud.githubusercontent.com/assets/109109/23374433/30d2ca26-fd1c-11e6-9daf-7aaa7b3c6d16.png)
![screenshot_2017-02-27_18-38-57](https://cloud.githubusercontent.com/assets/109109/23374435/32cfd558-fd1c-11e6-8173-8cefc19e98c0.png)
![screenshot_2017-02-27_18-39-53](https://cloud.githubusercontent.com/assets/109109/23374436/34a31cb4-fd1c-11e6-8bc5-c3dd2ff436e3.png)

The cortex graphs have large troughs of 0-value data, which are not present in the prom graphs.

Missing data? query timeouts? bug in query engine?

**Comment by tomwilkie** [comment] 2017-02-28 13:56
I suspect issue is with dropped samples from prometheus retrieval -> cortex, there is a metric exported by prometheus which can be used to confirm this.  This could have be caused by high latency on Weave Cloud.  Ideas in https://github.com/prometheus/prometheus/issues/2445 would help if this is the case.

**Comment by Bplotka** [comment] 2017-03-01 11:39
+1 Cool, this looks like the issue I have seen as well on my side.

**Comment by Bplotka** [comment] 2017-03-01 13:21
In my case the problem was with different sample values between plain prom and cortex. I am using grafana as my dashboards.

All dashboards are for query including one aggregation rule:
```
sum(code:grpc_server_handled_total:rate1m) BY (job)
```

where `code:grpc_server_handled_total:rate1m` rule is defined in plain prom over counter as:
```
code:grpc_server_handled_total:rate1m{} = sum(rate(grpc_server_handled_total[1m])) BY (job, grpc_code)
```
All dashboard are set for the same time range.

Results for plain prom:
![image](https://cloud.githubusercontent.com/assets/6950331/23458676/239a8628-fe75-11e6-83bb-23d452edf121.png)

Results for Cortex:
![image](https://cloud.githubusercontent.com/assets/6950331/23458681/2916952e-fe75-11e6-8d64-3bd03377ae46.png)

We can see that Cortex are not really giving 0-values, rather keeping last seen values for some samples. That would be understandable if the queried metric was a **gauge** (?), but it is just aggregation rule over **counter** which is simply seen as `# TYPE code:grpc_server_handled_total::rate1m untyped`. Not sure how missing values are handled in that case and why I am not seeing 0-values and rather last seen value. 

Additionally this query (aggregation over raw counter):
```
sum(rate(grpc_server_handled_total[1m])) BY (job)
```
...gives the same values for plain Prom and Cortex in the same timespan (:

Could it be the same issue?

**Comment by Bplotka** [comment] 2017-03-04 16:43
After 1 day run with real S3 and DynamoDB , spotted a lot of these issues:
![image](https://cloud.githubusercontent.com/assets/6950331/23580396/f95d8dca-00f8-11e7-9423-ecbaf465a678.png)

Sometimes really drastic:
![image](https://cloud.githubusercontent.com/assets/6950331/23580406/29b59864-00f9-11e7-81c9-2493cd08dff7.png)

However I don't even scaled Ingesters & Distributors yet. Will try to dive into Cortex metrics more and do a second try in next days.

**Comment by Bplotka** [comment] 2017-03-07 09:11
Tried to repro that again... All the time series I looked, looks perfectly the same between Cortex and Plain Prom ^^ I did not change anything between runs, except adding metrics from Cortex services and maybe cluster was not that loaded (which means -> less TS). Will try to schedule more jobs which increase number of unique ts.

**Comment by tomwilkie** [comment] 2017-03-07 11:04
Cool, almost definitely dropped samples then.  The improvements we're
making to Prometheus should stop this happening, but nothing is going to
stop it if the cluster is under provisioned.  You should monitor the remote
queue metrics:

- Sent batches:
`sum(irate(prometheus_remote_storage_sent_batch_duration_seconds_count[1m]))
by (queue)`
- Batch latency: `histogram_quantile(0.99,
sum(rate(prometheus_remote_storage_sent_batch_duration_seconds_bucket[5m]))
by (queue, le)) * 1e3`
- Queue capacity: `sum(prometheus_remote_storage_queue_capacity) by (queue)`
- Queue capacity:
`sum(prometheus_remote_storage_queue_length{job="monitoring/prometheus"})
by (queue)`

There should also be metric for number of dropped samples and failed
batches somewhere.

**Comment by Bplotka** [comment] 2017-03-07 12:10
That is super useful, thanks!

**Comment by Bplotka** [comment] 2017-03-08 17:00
After some tests and a lot of analysed graphs I am pretty sure my issue is NOT related to Prom issue. 

1) Between Monday and Wednesday, by accident I revoked access to S3, so Cortex was running **without** any persistent storage. Surprisingly I could query just fine , and everything worked including my repro case. I think that's one proof, that all the needed samples were actually sent from Prometheus.

2) Today I was analysing second run from yesterday's night with proper access (so persistent AWS storage was available) and could easily reproduce the issue:
![image](https://cloud.githubusercontent.com/assets/6950331/23711101/c8516014-0416-11e7-8669-604fb57152d6.png)
(Graphs for exactly the same metric as stated above). Time range, quite big: ~16h 

For the same time, not really any bottleneck for Prometheus remote send:
![image](https://cloud.githubusercontent.com/assets/6950331/23711596/350f1b1e-0418-11e7-897d-c2b94b8cc087.png)

The problem seems to be with querier or data stored in memcached, because when I tried to query with very short time range it worked just fine! (any time range, maximum ~2,5h wide):
![image](https://cloud.githubusercontent.com/assets/6950331/23711727/976b4b52-0418-11e7-80a7-0762b5e7b656.png)

Especially when I tried again with wider time range (again, wrong values)
![image](https://cloud.githubusercontent.com/assets/6950331/23711770/bb8b3c2c-0418-11e7-9d50-e16be4f8beb5.png)
And just **refreshed**, surprisingly I got different results than before (wrong as well, but different):
![image](https://cloud.githubusercontent.com/assets/6950331/23711818/e37e80ae-0418-11e7-8ba6-95b53ce1372f.png)

There is no particular error/warning logs except this from time to time on querier:
```
time="2017-03-08T07:45:51Z" level=warning msg="Could not store chunks in chunk cache: memcache: connect timeout to 10.114.8.41:11211" source="chunk_store.go:271" 
```

And actually for sure, memcached was hitting some open fd problem:
```
k -n cortex logs memcached-3196442244-v0fb2
accept4(): Too many open files
accept4(): Too many open files
accept4(): Too many open files
accept4(): Too many open files
accept4(): Too many open files
accept4(): Too many open files
accept4(): Too many open files
accept4(): Too many open files
accept4(): Too many open files
accept4(): Too many open files
accept4(): Too many open files
accept4(): Too many open files
accept4(): Too many open files
accept4(): Too many open files
accept4(): Too many open files
accept4(): Too many open files
accept4(): Too many open files
accept4(): Too many open files
accept4(): Too many open files
accept4(): Too many open files
accept4(): Too many open files
accept4(): Too many open files
accept4(): Too many open files
accept4(): Too many open files
accept4(): Too many open files
accept4(): Too many open files
accept4(): Too many open files
accept4(): Too many open files
accept4(): Too many open files
accept4(): Too many open files
accept4(): Too many open files
accept4(): Too many open files
accept4(): Too many open files
accept4(): Too many open files
accept4(): Too many open files
accept4(): Too many open files
accept4(): Too many open files
accept4(): Too many open files
```
No time-stamp though, so not sure when it was happening. At the time I was querying memcache, it was not logging these. Unfortunately don't have metric for open FD for memcached. Just by curiosity I nuked Memcached and.. it started to work a lot better (even for long time range):
![image](https://cloud.githubusercontent.com/assets/6950331/23713991/a08a5244-041f-11e7-8ebb-e95bd71e6e44.png)

As a conclusion it looks like some data was malformed on caching side (maybe because lack of open file descriptors), but that would not explain why sometimes I got non deterministic results. Additionally with increased time range the reproduction is more likely to happen.

**Comment by tomwilkie** [comment] 2017-03-08 18:31
Hmmm interesting!  Thanks for looking into this.  If we were occasionally
missing chunks from memcache and not getting them from S3, it would be a
bug here:

https://github.com/weaveworks/cortex/blob/master/chunk/chunk_cache.go#L122

or here:

https://github.com/weaveworks/cortex/blob/master/chunk/chunk_store.go#L247

I guess what could be happening is that we get incomplete chunk data back
from memcache, but don't get an error?  We could add checksums to catch
this.  But that seems unlikely.  Especially if its persistent - maybe we
encoded the chunk data incorrectly?

Also, could these error be related to the FD leak issue?

**Comment by Bplotka** [comment] 2017-03-09 09:23
> Also, could these error be related to the FD leak issue?

Do you mean https://github.com/weaveworks/cortex/issues/319? I don't think so, this is from runs where all the services on host (beside these Prom does not scrape) had pretty stable number of FDs:
![image](https://cloud.githubusercontent.com/assets/6950331/23743357/36296e1a-04a8-11e7-978d-d5c4bac9b14a.png)
This is from now and I can repro with scaled ingesters and memcache. Memcached has no error suggesting too many open files.

Additionally on my hosts (CoreOS 1325.1.0), right now (while running Cortex):
```
$ sysctl fs.file-nr
fs.file-nr = 2752	0	5341379
$ sysctl fs.file-max
fs.file-max = 5341379
```
I think that the Memcached log and too many open FD could be a red herring here.

**Comment by Bplotka** [comment] 2017-03-09 09:27
Interesting bit here is why it works just fine for short-time range (small number of samples in chunk?) I can probably even figure out exactly the number above which I have wrong data...

**Comment by tomwilkie** [comment] 2017-03-09 10:01
Another possibility is it could be a bug in how we merge recent results (from the ingesters) with results from the chunk store.  Am looking into it.

**Comment by Bplotka** [comment] 2017-03-09 13:06
The most interesting thing for me is why you cannot reproduce this issue on your side and I can.

I have an update as well, but for being clear here I would vote for moving my issue to another ticket, since it is not the same as @rade's initially stated issue.

Essentially I can see non deterministic drops when I am doing `rate` function over my metric. Like this (zoomed to just drop):
![image](https://cloud.githubusercontent.com/assets/6950331/23751338/c412de12-04c8-11e7-9329-9fbaca1dcd50.png)

The 1st  and 2nd graph on the left "screen" are with:
```
rate(grpc_server_handled_total{job="$job"}[5m])
```
Left is Cortex, next to it Prom.

3rd and 4th graph on the right screen has just the same raw metric:
```
grpc_server_handled_total{job="$job"}
```
For both Cortex and Prom as you can see 3rd and 4th have the same values as expected, so where this drop came from? Same for `increase`

Surprisingly `irate` works just fine.

My first guess would be to check the Prometheus version we are using and Cortex is using internally.

@tomwilkie you idea is reasonable as well

**Comment by Bplotka** [comment] 2017-03-09 14:25
Ok dug even deeper (based on @tomwilkie advices) and even from pure API I have the same results (which proofs that Grafana is right - this time ^^)

For query (unrated): `query_range?query=grpc_server_handled_total%7Bjob%3D%22ironman%22%2C%20grpc_code%3D%22OK%22%2C%20grpc_method%3D%22HealthCheck%22%2C%20instance%3D%2210.114.11.61%3A14444%22%7D&start=1489025974&end=1489026013&step=2`
Plain Prometheus and Cortex matches

For rated they does not. 

Since we are using Prom `9688a312edb772413f4a0f3b60e16aa77710d10b` (from 20 Jun) and
I think (from looking on vendor) Cortex is using `07491c9f1bf51fc985c8370ea43282d539cec9e7` so pretty new (10 days ago) there might be a difference in implementation

**Comment by Bplotka** [comment] 2017-03-09 14:37
Checked raw range data (as @juliusv  suggested) using instant query and can see missing data...
Cortex:
```
{ 
  "status": "success",
  "data": {
    "resultType": "matrix",
    "result": [
      {
        "metric": {
          "__name__": "grpc_server_handled_total",
          "component": "ironman",
          "grpc_code": "OK",
          "grpc_method": "HealthCheck"
        },
        "values": [
          [
            1489069586.651,
            "18796"
          ],
          [
            1489069601.674,
            "18799"
          ],
          [
            1489069616.651,
            "18802"
          ],
          [
            1489069631.651,
            "18805"
          ],
          [
            1489069646.651,
            "18808"
          ],
          [
            1489069661.651,
            "18811"
          ],
          [
            1489069676.651,
            "18814"
          ],
          [
            1489069691.651,
            "18817"
          ],
          [
            1489069706.651,
            "18820"
          ],
          [
            1489069736.651,
            "18826"
          ],
          [
            1489069751.651,
            "18829"
          ],
          [
            1489069766.651,
            "18832"
          ],
          [
            1489069781.651,
            "18835"
          ],
          [
            1489069796.651,
            "18838"
          ],
          [
            1489069811.651,
            "18841"
          ],
          [
            1489069826.651,
            "18844"
          ],
          [
            1489069841.651,
            "18847"
          ],
          [
            1489069856.651,
            "18850"
          ],
          [
            1489069871.651,
            "18853"
          ]
        ]
      }
    ]
  }
}
```
Prom:
```
{
  "status": "success",
  "data": {
    "resultType": "matrix",
    "result": [
      {
        "metric": {
          "__name__": "grpc_server_handled_total",
          "component": "ironman",
          "grpc_code": "OK",
          "grpc_method": "HealthCheck"
        },
        "values": [
          [
            1489069586.651,
            "18796"
          ],
          [
            1489069601.674,
            "18799"
          ],
          [
            1489069616.651,
            "18802"
          ],
          [
            1489069631.651,
            "18805"
          ],
          [
            1489069646.651,
            "18808"
          ],
          [
            1489069661.651,
            "18811"
          ],
          [
            1489069676.651,
            "18814"
          ],
          [
            1489069691.651,
            "18817"
          ],
          [
            1489069706.651,
            "18820"
          ],
          [
            1489069721.651,
            "18823"
          ],
          [
            1489069736.651,
            "18826"
          ],
          [
            1489069751.651,
            "18829"
          ],
          [
            1489069766.651,
            "18832"
          ],
          [
            1489069781.651,
            "18835"
          ],
          [
            1489069796.651,
            "18838"
          ],
          [
            1489069811.651,
            "18841"
          ],
          [
            1489069826.651,
            "18844"
          ],
          [
            1489069841.651,
            "18847"
          ],
          [
            1489069856.651,
            "18850"
          ],
          [
            1489069871.651,
            "18853"
          ]
        ]
      }
    ]
  }
}
```

Missing single sample from Plain Prom:
```
[
            1489069721.651,
            "18823"
 ],
```

**Comment by Bplotka** [comment] 2017-03-09 16:54
Additionally, I just found that not all my data was flushed... (because of too low throughput) so I might fetching data from memcached

**Comment by tomwilkie** [comment] 2017-03-14 10:05
AFIACT there are three correctness issues we're tracking:
- Incorrect query results, with the wrong labels - #303
- Missing data from queries, dues to bugs in the schema - #337 
- Inconsistent results from `rate()` queries (this issue).

I wonder is the third issue is actually the same as the first...

**Comment by tomwilkie** [comment] 2017-03-15 22:50
There was another bug in the handling of dynamo pagination - see 8971b9063928399180992d8dd5c74672856e4603.

With all the recent fixes, would you mind testing for this issue again @Bplotka?

**Comment by Bplotka** [comment] 2017-03-16 07:26
Nice! Will do today.

**Comment by Bplotka** [comment] 2017-03-16 12:06
Running Cortex for 3,5h and so far perfect results on different metrics 
e.g: 
![image](https://cloud.githubusercontent.com/assets/6950331/23995143/2db04298-0a40-11e7-8a5b-162c02ceb8c3.png)

Will feel confident after leaving that for a night (:

**Comment by tomwilkie** [comment] 2017-03-16 12:09
Sweet!  I'll close this, if you do find issues lets open a fresh one.

**Closed by tomwilkie** 2017-03-16 12:09 UTC
Labels: bug
